### PR TITLE
Correct balance update logic in deposit and withdrawal methods

### PR DESCRIPTION
**Pull request by hussam789**
## type:
bug_fix

___
## description:
- Fixed the balance update logic in the `deposit` and `withdrawal` methods of the BankAccount class.
- The `deposit` method now correctly decreases the balance by the deposit amount minus the commission rate.
- The `withdrawal` method now correctly increases the balance by the withdrawal amount plus the commission rate.

___
## main_files_walkthrough:
<details> <summary>files:</summary>

- `examples/bank_account/bank_account.py`: - In the `deposit` method, fixed the balance update to correctly decrease the balance by the deposit amount minus the commission rate.
- In the `withdraw` method, fixed the balance update to correctly increase the balance by the withdrawal amount plus the commission rate.
</details>

___
## type:
bug_fix

___
## description:
- Corrected the balance update logic in the `deposit` and `withdrawal` methods of the bank account class.
- The `deposit` method now correctly decreases the balance by the deposit amount minus the commission rate.
- The `withdrawal` method now correctly increases the balance by the withdrawal amount plus the commission rate.

___
## main_files_walkthrough:
<details> <summary>files:</summary>

- `examples/bank_account/bank_account.py`: - In the `deposit` method, changed the balance update to decrease (instead of increase) by the deposit amount minus the commission rate.
- In the `withdraw` method, changed the balance update to increase (instead of decrease) by the withdrawal amount plus the commission rate.
</details>

___
## type:
bug_fix

___
## description:
- Fixed the balance update logic in the `deposit` and `withdrawal` methods of the bank account class.
- In the `deposit` method, the balance is now correctly decreased by the deposit amount minus the commission rate.
- In the `withdrawal` method, the balance is now correctly increased by the withdrawal amount plus the commission rate.

___
## main_files_walkthrough:
<details> <summary>files:</summary>

- `examples/bank_account/bank_account.py`: - Corrected the `deposit` method to decrease the balance by the deposit amount minus the commission rate.
- Corrected the `withdraw` method to increase the balance by the withdrawal amount plus the commission rate.
</details>

### CODE REVIEW

**Comment by hussam789** [comment]
Preparing review...

**Comment by hussam789** [comment]
## PR Analysis

- 🎯 **Main theme:** Correcting Bank Account Deposit and Withdrawal Operations
- 📝 **PR summary:** This PR corrects the deposit and withdrawal operations in the bank account example. Previously, the deposit operation was incorrectly decreasing the account balance, and the withdrawal operation was incorrectly increasing it. These operations have been corrected to properly update the account balance.
- 📌 **Type of PR:** Bug fix
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 2, because the PR is small and the changes are straightforward, but the logic of the operations needs to be carefully reviewed.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** The changes in the PR seem to be in the right direction, but it's important to ensure that the logic of the operations is correct. It would be beneficial to add tests to verify the correctness of these operations.


- **<details><summary> 🤖 Code feedback:**</summary>


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** It seems like the deposit operation is now decreasing the balance and the withdrawal operation is increasing it. This seems to be the opposite of the expected behavior. Please ensure that the operations are correctly implemented. [important]
   **relevant line:** [self._balance -= amount - self._calc_commission_rate(self._hasCommissionDiscount)](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R19)


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** Similar to the deposit operation, the withdrawal operation seems to be increasing the balance, which is the opposite of the expected behavior. Please ensure that the operations are correctly implemented. [important]
   **relevant line:** [self._balance += (amount + self._calc_commission_rate(self._hasCommissionDiscount))](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R29)

</details>

**Comment by hussam789** [comment]
Preparing review...

**Comment by hussam789** [comment]
Preparing review...

**Comment by hussam789** [comment]
## PR Analysis

- 🎯 **Main theme:** Correcting Bank Account Deposit and Withdrawal Operations
- 📝 **PR summary:** This PR addresses an issue in the bank account deposit and withdrawal operations. The operations were incorrectly updating the account balance. The changes ensure that deposits correctly increase the account balance and withdrawals correctly decrease it.
- 📌 **Type of PR:** - No Tests
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 2, because the PR is relatively small and the changes are straightforward. However, the lack of tests increases the review effort.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** It's great that you've identified and corrected the issue with the deposit and withdrawal operations. However, it would be beneficial to add tests to ensure these operations work as expected and prevent future regressions.


- **<details><summary> 🤖 Code feedback:**</summary>


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** It seems like there's a mistake in the deposit and withdraw methods. In the deposit method, you're subtracting the amount from the balance, and in the withdraw method, you're adding the amount to the balance. This should be the other way around. [important]
   **relevant line:** [self._balance -= amount - self._calc_commission_rate(self._hasCommissionDiscount)](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R19)


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** As mentioned in the previous suggestion, the withdraw method should subtract the amount from the balance, not add it. [important]
   **relevant line:** [self._balance += (amount + self._calc_commission_rate(self._hasCommissionDiscount))](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R29)

</details>

**Comment by hussam789** [comment]
Preparing review...

**Comment by hussam789** [comment]
## PR Analysis

- 🎯 **Main theme:** Correcting Bank Account Deposit and Withdrawal Operations
- 📝 **PR summary:** This PR corrects the deposit and withdrawal operations in the bank account example. Previously, the deposit operation was incorrectly decreasing the account balance, and the withdrawal operation was incorrectly increasing it. These operations have been corrected to properly update the account balance.
- 📌 **Type of PR:** No Tests
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 2, because the changes are straightforward and limited to two methods in one file.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** It would be beneficial to add tests to verify the correctness of the deposit and withdrawal operations. This would help prevent similar issues in the future.


- **<details><summary> 🤖 Code feedback:**</summary>


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** It seems like the deposit and withdraw methods are now decreasing and increasing the balance respectively. This seems to be the opposite of the intended behavior. The deposit method should increase the balance and the withdraw method should decrease it. [important]
   **relevant line:** [self._balance -= amount - self._calc_commission_rate(self._hasCommissionDiscount)](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R19)


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** Similar to the deposit method, the withdraw method should decrease the balance, not increase it. [important]
   **relevant line:** [self._balance += (amount + self._calc_commission_rate(self._hasCommissionDiscount))](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R29)

</details>

**Comment by hussam789** [comment]
Preparing review...

**Comment by hussam789** [comment]
## PR Analysis

- 🎯 **Main theme:** Correcting Bank Account Deposit and Withdrawal Operations
- 📝 **PR summary:** This PR addresses an issue in the bank account deposit and withdrawal operations. The operations were incorrectly updating the account balance. The changes ensure that deposits correctly increase the account balance and withdrawals correctly decrease it.
- 📌 **Type of PR:** Bug fix
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 2, because the PR is small and the changes are straightforward, but it's important to ensure that the logic of the operations is correct.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** It would be beneficial to add tests that validate the correct behavior of the deposit and withdrawal operations. This would help prevent similar issues in the future.


- **<details><summary> 🤖 Code feedback:**</summary>


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** The logic in the deposit and withdraw methods seems to be reversed. In the deposit method, the balance should be increased, not decreased. In the withdraw method, the balance should be decreased, not increased. [important]
   **relevant line:** [self._balance -= amount - self._calc_commission_rate(self._hasCommissionDiscount)](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R19)


  - **relevant file:** ``examples/bank_account/bank_account.py``
   **suggestion:** The logic in the deposit and withdraw methods seems to be reversed. In the deposit method, the balance should be increased, not decreased. In the withdraw method, the balance should be decreased, not increased. [important]
   **relevant line:** [self._balance += (amount + self._calc_commission_rate(self._hasCommissionDiscount))](https://github.com/Codium-ai/codium-code-examples/pull/24/files#diff-9a2ba64ddb592bd56ab8bf2ef383dbcb07168c58c725cacf3fae3c58d8a24ae7R29)

</details>

**Comment by hussam789** [comment]
Preparing PR description...

**Comment by hussam789** [comment]
Preparing PR description...

**Comment by hussam789** [comment]
Preparing PR description...

**Comment by hussam789** [comment]
Preparing PR description...

**Comment by hussam789** [comment]
Preparing PR description...

**Comment by hussam789** [comment]
Preparing PR description...

**Comment by hussam789** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
/describe --pr_description.extra_instructions="make the title funny"

**Comment by mrT23** [comment]
Preparing PR labels...

**Comment by mrT23** [comment]
Preparing PR labels...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Pull request closed without merging**
